### ISSUE TITLE
Fonts are absent

### ISSUE THREAD

**Issue by abrarishere** [rubiin/nfdl#2]
It only creates .fonts(empty folder). There is not any font even it is sais that font has been downloaded

It is resolved

**Comment by abrarishere** [comment]
> It only creates .fonts(empty folder). There is not any font even it is sais that font has been downloaded

Oh it is resolved

**Comment by rubiin** [comment]
let me try to resolve this asap

**Comment by rubiin** [comment]
Also could you paste in the command you are using so I can reproduce the issue

**Comment by abrarishere** [comment]
> Also could you paste in the command you are using so I can reproduce the issue

oh it is solved may be i wasn't using space to select them or Internet issue

**Comment by rubiin** [comment]
Thanks for letting me know :)
